### PR TITLE
Code Review #2

### PR DESCRIPTION
**Pull request by MarcusAl**
Made new PR from feature branch after the advice from a previous Code Review. Module name changed, and module methods fixed.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Marcus Allen & Salley Iddrisu ** 
Nice job following the requirements from the previous TSE :muscle:  :muscle: 
We still need to do some additional improvements before you can go ahead:

- [x] Don't edit the original rubocop file
- [x] #my_each returns an Enumerator if no block is given
    `[1,2,3].my_each.class == Enumerator`
- [x] #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self
        `[1,2,3,4,5].each(&proc{|n| n%2}) == [1,2,3,4,5].my_each(&proc{|n| n%2})`
- [x] #my_each when a block is given when self is a range returns the range itself after
calling the given block once for each element in self
        `[1,2,3].my_each(&proc{|x| x>2}) == [1,2,3]`
- [x] #my_each_with_index returns an enumerator if no block is given
    `[1,2,3].my_each_with_index.class == Enumerator`
- [x] #my_each_with_index when a block is given when self is an array
     ```
      concat1=''
      [1,2,3,4].each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      [1,2,3,4].my_each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
     ```
       returns the array itself after calling the given block once for each element in self
        `[1,2,3,4,5].each_with_index(&proc{|n| n%2}) == [1,2,3,4,5].my_each_with_index(&proc{|n| n%2})`
- [x] #my_each_with_index when a block is given when self is a range
     ```
      concat1=''
      (1..4).each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      (1..4).my_each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
     ```
       returns the range itself after calling the given block once for each element in self
        `(1..3).my_each_with_index(&proc{|x| x>2}) == (1..3)`
- [x] #my_each_with_index when a block is given when self is a range
     ```
      concat1=''
      (1..4).each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      (1..4).my_each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
     ```
       behaves like #each_with_index calls the given block once for each element in self
- [x] #my_each_with_index when a block is given when self is a hash
     ```
      concat1=''
      { a: 1, b: 2, c: 3, d: 4}.each_with_index(&proc{|n, i| concat1+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat2=''
      { a: 1, b: 2, c: 3, d: 4}.my_each_with_index(&proc{|n, i| concat2+='n: '+n.to_s+', i: '+i.to_s+'+++'})
      concat1 == concat2
    ```
       behaves like #each_with_index calls the given block once for each element in self
- [x] #my_select returns an array containing all elements of enum for which the given block returns a true value
    `[1,2,3,4,5].select(&proc{|x| x>2}) == [1,2,3,4,5].my_select(&proc{|x| x>2})`
- [x] #my_select returns an array containing all elements of enum for which the given block returns a true value::range
    `(1..3).select(&proc{|x| x>2}) == (1..3).my_select(&proc{|x| x>2})`
- [x] #my_select returns an enumerator if no block is given
    `[1,2,3,4].my_select.class==Enumerator`
- [x] #my_all? returns false if the block returns false or nil::range
    `(1..3).all?(&proc{|x| x%2==0}) == (1..3).my_all?(&proc{|x| x%2==0})`
- [x] #my_all? when no block or argument is given returns false when one of the collection members are false or nil
      `[true,[true],false].all? == [true,[true],false].my_all?`
- [x] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer        
      `[1,2,3].all?(Integer) == [1,2,3].my_all?(Integer)`
- [x] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric        
      `[1,-2,3.4].all?(Numeric) == [1,-2,3.4].my_all?(Numeric)`
- [x] #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
      `['word',1,2,3].all?(Integer) == ['word',1,2,3].my_all?(Integer)`
- [x] #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
      `['car', 'cat'].all?(/a/) == ['car', 'cat'].my_all?(/a/)`
- [x] #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
      `[5,5,5].all?(5) == [5,5,5].my_all?(5)`
- [x] #my_all? when a pattern other than Regex or a Class is given returns false if any 
of the collection does not match the pattern
      `[5,5,[5]].all?(5) == [5,5,[5]].my_all?(5)`
- [x] #my_any? returns false if the block ever returns a value false or nil::range
    `(1..3).any?(&proc{|x| x==0}) == (1..3).my_any?(&proc{|x| x==0})`
- [x] #my_any? when no block or argument is given returns false if at least one of the collection is not true
      `[false, 0].any? == [false, 0].my_any?`
- [x] #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
      `['dog', 'cat'].any?(/z/) == ['dog', 'cat'].my_any?(/z/)`
- [x] #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern       
      `['dog','car'].any?('cat') == ['dog','car'].my_any?('cat')`
- [x] #my_none? returns false if the block ever returns true for all elements::range
    `(1..3).none?(&proc{|num| num%2==0}) == (1..3).my_none?(&proc{|num| num%2==0})`
- [x] #my_none? when no block or argument is given returns false only if one of the collection members is true
      `[false, nil,[]].none? == [false, nil,[]].my_none?`
- [x] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
      `[true,[]].none?(String) == [true,[]].my_none?(String)`
- [x] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric      
      `[true,[]].none?(Numeric) == [true,[]].my_none?(Numeric)`
- [x] #my_none? when a class is passed as an argument returns false if any of the collection is a member of such class
      `['',[]].none?(String) == ['',[]].my_none?(String)`
- [x] #my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex
      `['dog','cat'].none?(/x/) ==  ['dog','cat'].my_none?(/x/)`
- [x] #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
      `['dog', 'cat'].none?(/d/) == ['dog', 'cat'].my_none?(/d/)`
- [x] #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern  
      `['dog','car'].none?(5) == ['dog','car'].my_none?(5)`
- [x] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern  
      `[5,'dog','car'].none?(5) == [5,'dog','car'].my_none?(5)`
- [x] #my_map returns an Enumerator if no block is given
    `[1,2,3].map.class==[1,2,3].my_map.class`
- [ ] #my_inject raises a 'LocalJumpError' when no block or argument is given
    ```
    begin
      [1,2,3,4].my_inject
    rescue LocalJumpError
      true
    end
    ```

- [x] #my_inject searches for the longest word in an array of strings
    `['to','four','tri'].my_inject(&proc{|a,b| [a,b].max_by{|m| m.length}}) == ['to','four','tri'].inject(&proc{|a,b| [a,b].max_by{|m| m.length}})`
- [x] #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block
      `[1,2,3].inject(&proc{|total, num| total*num}) == [1,2,3].my_inject(&proc{|total, num| total*num})`
- [x] #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range
      `(1..3).inject(&proc{|total, num| total*num}) == (1..3).my_inject(&proc{|total, num| total*num})`
- [x] #my_inject when a block is given with an initail value combines all elements of enum by applying a binary operation, specified 
by a block
      `(1..3).inject(4) { |prod, n| prod * n } == (1..3).my_inject(4) { |prod, n| prod * n }`
- [x] #my_inject when a symbol is specified without an initail value combines each element of the collection by applying the symbol as a named method
      `[1,2,3].inject(:+) == [1,2,3].my_inject(:+)`
- [x] #my_inject when a symbol is specified without an initail value combines each element of the collection by applying the symbol as a named method:range
      `(1..9).inject(:+) == (1..9).my_inject(:+)`
- [x] #my_inject when a symbol is specified with an initail value combines each element
of the collection by applying the symbol as a named method
      `[1,2,3].inject(4, :*) == [1,2,3].my_inject(4, :*)`
- [x] #my_inject when a symbol is specified with an initail value combines each element
of the collection by applying the symbol as a named method::range
      `(1..3).inject(4, :*) == (1..3).my_inject(4, :*)`
- [x] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject
    `multiply_els([1,2,3]) == 6`
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @CacheMeGifYouCan and @juxsalley 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [x] `#my_all?` when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [x] `#my_count` returns the number of items in enum through enumeration
- [x] `#my_count` returns the number of items in enum through enumeration::range
- [x]  `#my_count `counts the number of items in enum that are equal to item if an argument is given
- [x] `#my_count `counts the number of elements yielding a true value if a block is given
- [x] `#my_count ` does not mutate the original array
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Marcus Allen & Salley Iddrisu** 
Nice job with improvements to your project :muscle:  :muscle:
Now your method passes most of the tests :clap: :clap: :clap:  
We still need to fix some issues before the approval:

- [x] Don't edit the original rubocop config file
- [x] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer        
      `[1,2,3].all?(Integer) == [1,2,3].my_all?(Integer)`
- [x] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric        
      `[1,-2,3.4].all?(Numeric) == [1,-2,3.4].my_all?(Numeric)`
- [x] #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
      `['car', 'cat'].all?(/a/) == ['car', 'cat'].my_all?(/a/)`
- [x] #my_count returns the number of items in enum through enumeration::range
    `(1..3).count == (1..3).my_count`
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by LamiaSristy — CHANGES_REQUESTED** [review]
# Status: Change Required. ♻️

**Thank you for making all the changes, asked by the previous reviewer**.

**Your README is very organized, especially the adding screenshots is presenting an insight of your work. Good Job. 👏 👏 👏**

Still, there is one thing you need to change.

# You can't edit the original rubocop.yml file.

**For solution:**
You should either refactor the code or disable the rubocop rules with inline comments for the affected files, in your `enumerables.rb` file.

**I know it can be very frustrating getting continuous changes to make, but it is everyday work in a developer's life.**

Keep up the spirit always.

Feel free to reach me on slack @lamiasristy 🙋

 Happy Coding 💻

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

Congratulations on completing your project and taking the time to implement the changes requested by the previous TSEs.  

Your effort towards completing this project is commendable. Keep up the good work 🍷 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
