### PR TITLE
Code Review Request

### PR DESCRIPTION
**Pull request by MarcusAl**
Requesting a code review for our Enumerable methods project

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @CacheMeGifYouCan and @juxsalley :clap: :clap:
#### You have done a good so far :+1: However, some of the methods are failing the required tests. Check my comments below :point_down:

#### Note: For convenience, I will add some values here that can be used to test the methods.

```
array = [6, 19, 19, 25, 7, 30, 20, 27, 22, 19, 18, 29, 12, 31, 2, 12, 0, 32, 1, 20]
block = proc { |num| num < (0 + 9) / 2 }
rang = Range.new(5, 50)
false_block = proc { |num| num > 9 }
true_block = proc { |num| num <= 9 }
numbers = [1, 2i, 3.14]
words = %w[programmer computer house car]
true_any_array = [nil, false, true, []]
false_any_array = [nil, false, nil, false]
true_array = [1, true, 'hi', []]
false_array = [1, false, 'hi', []]

```
##### `my_each`
 - when a block is given: when self is a range should return the range itself after calling the given block once for each element in self: `rang.my_each(&block) == rang.each(&block)`

##### `my_each_with_index`
 - when a block is given: when self is a range should return the range itself after calling the given block once for each element in self: `rang.my_each(&block) == rang.each(&block)`

##### `my_select`
 - should return an array containing all elements of enum for which the given block returns a true value::range - `rang.my_select(&block) == rang.select(&block)`

##### `my_all?`
 - should return false if the block returns false or nil::range - `rang.my_all?(&false_block) == rang.all?(&false_block)`
 - when no block or argument is given should return true when none of the collection members are false or nil: `true_array.my_all? == true_array.all?`
 - when no block or argument is given it should return false when one of the collection members is false or nil: `false_array.my_all? == false_array.all?`
 - when a class is passed as an argument it should return true if all of the collection is a member of such class::Integer - `array.my_all?(Integer) == array.all?(Integer)`
 - when a class is passed as an argument it should return true if all of the collection is a member of such class::Numeric - `numbers.my_all?(Numeric) == numbers.all?(Numeric)`
 - when a class is passed as an argument it should return false if any of the collection is not a member of such class: `array[2] = 'string'` `array.my_all?(Integer) == array.all?(Integer)`
 - when a Regex is passed as an argument it should return true if all of the collection matches the Regex: `words.my_all?(/d/) == words.all?(/d/)`
 - when a Regex is passed as an argument it should return false if any of the collection does not match the Regex: `words.my_all?(/o/) == words.all?(/o/)`
 - when a pattern other than Regex or a Class is given it should return true if all of the collection matches the pattern: `array.my_all?([7, 7, 7, 7]) == array.all?([7, 7, 7, 7])`
 - when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern: `array.my_all?(3) == array.all?(3)`

##### my_any?
 - It should return false if the block ever returns a value false or nil::range - `rang.my_any?(&false_block) == rang.any?(&false_block)`
 - when no block or argument is given it should return true if at least one of the collection is not false or nil: `true_array.my_any? == true_array.any?`
 - when no block or argument is given it should return false if at least one of the collection is not true: `false_array.my_any? == false_array.any?`
 - when a class is passed as an argument it should return true if at least one of the collection is a member of such class::Numeric - ` array.my_any?(Numeric) == array.any?(Numeric)`
 - when a class is passed as an argument it should return true if at least one of the collection is a member of such class::Integer - `words.my_any?(Integer) == words.any?(Integer)`
 - when a Regex is passed as an argument it should return true if any of the collection matches the Regex: `words.my_any?(/d/) == words.any?(/d/)`
 - when a Regex is passed as an argument it should return false if none of the collection matches the Regex: `words.my_any?(/z/) == words.any?(/z/)`
 - when a pattern other than Regex or a Class is given it should return false if none of the collection matches the pattern: `words.my_any?('cat') == words.any?('cat')`
 - when a pattern other than Regex or a Class is given it should return true if any of the collection matches the pattern: `words[2] = 'car'` `words.my_any?('cat') == words.any?('cat')`

##### `my_none?`
 - It should return false if the block ever returns true for all elements::range - `rang.my_none?(&false_block) == rang.none?(&false_block)`
 - when no block or argument is given it should return true only if none of the collection members is true
 - when no block or argument is given it should return false only if one of the collection members is true
 - when a class is passed as an argument it should return true if none of the collection is a member of such class
 - when a class is passed as an argument it should return true if none of the collection is a member of such class::Numeric
 - when a class is passed as an argument it should return false if any of the collection is a member of such class
 - when a Regex is passed as an argument it should return true if none of the collection matches the Regex
 - when a Regex is passed as an argument it should return false if any of the collection matches the Regex
 - when a pattern other than Regex or a Class is given it should return true only if none of the collection matches the pattern
 - when a pattern other than Regex or a Class is given it should return false only if one of the collection matches the pattern
 
##### my_count
 - counts the number of items in enum that are equal to an item if an argument is given

##### my_map
 - It should return a new array with the results of running a given block once for every element in enum::range
 - It should return an Enumerator if no block is given
 - executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum
 
#### my_inject
 - It searches for the longest word in an array of strings
 - when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
 - when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
 - when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
 - when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
 - when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
 - when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range

**_Note some of the variables provided for the testing of these methods needs to be edited before they can be used for testing some methods._**
 
#### _Reviewed by Temitayo Adeleke_

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes required
Hello team you are doing great so far in this project.
I have noted that you have not made the changes requested by the previous TSE.
Kindly make the changes before submitting another review.

### If you are stuck you can refer to the [Ruby Enumerable Docs](https://ruby-doc.org/core-2.6.4/Enumerable.html)

# Feel free to reach me on slack [Oloo Moses] incase of doubts or concerns

**Comment by codesalley** [comment]
> we've made all changes requested by the previous TSE

**Comment by MarcusAl** [comment]
Made changes to the enumerable in the enumerable.rb file as requested by the code reviewer.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

**Hey Team, Thanks for the great work and efforts into the project. There are a few changes I'll ask of you.**

### REQUIRED CHANGES: 💯 

- [ ] Always ensure to follow Github flow in all your projects. ` Development branch ` should be the default branch. A PR should be opened on from the ` feature branch ` to the ` development `. ` main branch ` should also be included amongst your branches. 😄 
- [ ] The main cause of your failed tests is because you named the module ` Enumerables `, and it should rather be ` Enumerable `. Kindly change this.
- [ ] Then implement all changes requested by the first reviewer, everything should work just fine on both ends once you change the module name.
### 
Make the requested changes and submit another CRR. 💯 

Happy Coding! 🍹 

Reach me on slack for a ChitChat: **Roy Mukuye**

**Pull request closed without merging**
